<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use kartik\file\FileInput;
use kartik\date\DatePicker;
use kartik\datetime\DateTimePicker;

/**
* @var yii\web\View $this
* @var app\models\Pendanaan $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="box box-info">
    <div class="box-body">
        <?php $form = ActiveForm::begin([
        'id' => 'Pendanaan',
        'layout' => 'horizontal',
        'enableClientValidation' => true,
        'errorSummaryCssClass' => 'error-summary alert alert-error'
        ]
        );
        ?>
        
			<?= $form->field($model, 'nama_pendanaan')->textInput(['maxlength' => true]) ?>
            
			<?= $form->field($model, 'uraian')->textarea(['rows' => 6]) ?>
			<?= $form->field($model, 'nominal')->textInput(['type'=>'number']) ?>
            <?=$form->field($model, 'pendanaan_berakhir')->widget(DateTimePicker::classname(), [
    'options' => ['placeholder' => 'Pilih Tanggal Pendanaan Berakhir'],
	'name' => 'event_time',
    'readonly' => true,
    'pluginOptions' => [
        'format' => 'yyyy-m-d H:i:s',
        'autocomplete' => "off",
        'autoclose'=>true,
    ],
]);?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'kategori_pendanaan_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\KategoriPendanaan::find()->all(), 'id', 'name'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['kategori_pendanaan_id'])),
    ]
); ?>
	    <?= $form->field($model, 'foto',[
                    
    'options' => ['tag' => false]])->widget(FileInput::classname(), [
'options' => ['accept' => 'file/*'],
'pluginOptions' => [
    'allowedFileExtensions' => ['png','jpg','jpeg'],
    'maxFileSize' => 6500,
    'showRemove' => false,
    'showUpload' => false,
    'showCaption' => false,
    'dropZoneEnabled' => false,
    'browseLabel' => 'Upload File',
],
]);?>   <hr/>
        <?php echo $form->errorSummary($model); ?>
        <div class="row">
            <div class="col-md-offset-3 col-md-10">
                <?=  Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                <?=  Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>