<?php

use app\models\KategoriPendanaan;
use app\models\Status;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\web\View;

/**
* @var yii\web\View $this
* @var yii\data\ActiveDataProvider $dataProvider
* @var app\models\search\PendanaanSearch $searchModel
*/

$this->title = 'Pendanaan';
$this->params['breadcrumbs'][] = $this->title;
?>

<p>
    <?= Html::a('<i class="fa fa-plus"></i> Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?>
</p>
<div class="box-body">

<div class="row">
    <div class="col-md-12">
        <label><strong>Pilih Tanggal Awal :</strong></label>
    </div>
    <div class="col-md-12">
        <input id="tanggal1" type="text" class="datepicker form-control"
               value="<?php echo date("Y-m-d"); ?>" style="text-align: center">
    </div>
</div>
<br/>
<div class="row">
    <div class="col-md-12">
        <label><strong>Pilih Tanggal Akhir :</strong></label>
    </div>
    <div class="col-md-12">
        <input id="tanggal2" type="text" class="datepicker form-control"
               value="<?php echo date("Y-m-d"); ?>" style="text-align: center">
    </div>
</div>
<br/>
<hr />

<div class="row">
    <div class="clearfix"></div>
    <div class="col-md-12">
        <a class="btn btn-success btn-block" id="cetak" target="_blank" >Export Excel</a>
    </div>
</div>
</div>

    <?php \yii\widgets\Pjax::begin(['id'=>'pjax-main', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>

    <div class="box box-info">
        <div class="box-body">
            <div class="table-responsive">
                <?= GridView::widget([
                'layout' => '{summary}{pager}{items}{pager}',
                'dataProvider' => $dataProvider,
                'pager'        => [
                'class'          => yii\widgets\LinkPager::className(),
                'firstPageLabel' => 'First',
                'lastPageLabel'  => 'Last'                ],
                'filterModel' => $searchModel,
                'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                'headerRowOptions' => ['class'=>'x'],
                'columns' => [
                    
                \app\components\ActionButton::getButtons(),
                
                'nama_pendanaan',
                // 'uraian:ntext',
                [
                    'attribute' => 'nominal',
                    'label' => 'Nominal',
                    'format' => 'raw',
                    'filter' => false,
                    'value' =>function ($model) {
            
                        return \app\components\Angka::toReadableHarga($model->nominal);
                
                    },
                ],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
            [
                'attribute'=>'user_id',

                'filter'    => false,
                'value' => function($model){
                    return $model->user->name;
                }
            ],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
            [
                'attribute'=>'kategori_pendanaan_id',
                'filter'    => ArrayHelper::map(KategoriPendanaan::find()->all(), 'id', 'name'),
                'value' => function($model){
                    return $model->kategoriPendanaan->name;
                }
            ],
            
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'attribute'=>'status_id',
                'format' => 'html',
                'filter'    => ArrayHelper::map(Status::find()->where(['like', 'name', 'pendanaan'])->all(), 'id', 'name'),
                'value' => function($model){
                    if($model->status == 1){
                        return '<span class="label label-warning">'.$model->status->name.'</span>';    
                    }
                    elseif($model->status == 2){
                        return '<span class="label label-success">'.$model->status->name.'</span>';    
                    }
                    elseif($model->status == 3){
                        return '<span class="label label-success">'.$model->status->name.'</span>';    
                    }
                    elseif($model->status == 4){
                        return '<span class="label label-success">'.$model->status->name.'</span>';    
                    }
                    elseif($model->status == 7){
                        return '<span class="label label-danger">'.$model->status->name.'</span>';    
                    }
                    elseif($model->status == 9){
                        return '<span class="label label-warning">'.$model->status->name.'</span>';    
                    }
                    elseif($model->status == 11){
                        return '<span class="label label-success">'.$model->status->name.'</span>';    
                    }
                }
            ],
            [
                'attribute' => 'pendanaan_berakhir',
                'format' => 'raw',
                'filter' => false,
                'value' => function ($model) {
                    return \app\components\Tanggal::toReadableDate($model->pendanaan_berakhir);
                }
            ],
            
            \app\components\ActionApproveButton::getButtons(),
			/*'foto'*/
                ],
                ]); ?>
            </div>
        </div>
    </div>

    <?php \yii\widgets\Pjax::end() ?>
<?php
$my_js = '
$(document).ready(function(){
$(".datepicker").datepicker({
format: "yyyy-mm-dd"
});
 $("#spinner").hide();
});
            $("#cetak").click(function() {
                var url = "'.Yii::$app->homeUrl.'pendanaan/export?"
                    + "t1=" + $("#tanggal1").val()
                    + "&t2=" + $("#tanggal2").val();

                window.open(url, "_blank","height=200,width=150");
            });
   ';
$this->registerJs($my_js, View::POS_END);
?>

