<?php

use dmstr\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\KelompokRekening $catatanUsaha
 */
?>
<div class="giiant-crud pencatatan-usaha-view">
    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="box box-info">
        <div class="box-body">
            <?php
            // var_dump($catatanUsaha);die;
            if ($model != null ) {
            ?>
                <?php $this->beginBlock('app\models\Pembayaran'); ?>

<?= DetailView::widget([
    'model' => $model,
    'attributes' => [

        [
            'attribute' => 'pendanaan_id',
            'value' => function ($model) {
                return $model->pendanaan->nama_pendanaan;
            }
        ],
        'kode_transaksi',
        'nama',
        [
            'attribute' => 'nominal',
            'label' => 'Nominal',
            'format' => 'raw',
            'filter' => false,
            'value' => function ($model) {

                return \app\components\Angka::toReadableHarga($model->nominal);
            },
        ],
        [
            'attribute' => 'jumlah_lembaran',
            'format' => 'raw',
            'filter' => false,
            'value' => function ($model) {

                return $model->jumlah_lembaran." Lembar";
            },
        ],
        // [
        //     'attribute' => 'jenis_pembayaran_id',
        //     'format' => 'raw',
        //     'value' => function ($model) {
        //         if($model->jenis_pembayaran_id != null){
        //             return $model->jenisPembayaran->nama_jenis;
        //         }else{
        //             return "Belum Melakukan Pembayaran";
        //         }
        //     }
        // ],
        [
            'attribute' => 'bukti_transaksi',
            'format' => 'html',
            'value' => function ($model) {
                return Html::img(\Yii::$app->request->BaseUrl . '/uploads/pembayaran/bukti_transaksi/' . $model->bukti_transaksi, ['width' => 100]);
            },
        ],
        [
            'attribute' => 'jenis_pembayaran_id',
            'value' => function ($model) {
                return $model->jenis_pembayaran_id;
            }
        ],
        // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
        [
            'attribute' => 'user_id',
            'value' => function ($model) {
                return $model->user->name;
            }
        ],
        // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
        [
            'attribute' => 'created_at',
            'label' => 'Tanggal Buat Pembayaran',
            'format' => 'raw',
            'filter' => false,
            'value' => function ($model) {
                return \app\components\Tanggal::toReadableDate($model->created_at);
            }
        ],
        // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
        [
            'attribute' => 'tanggal_upload_bukti',
            'format' => 'raw',
            'filter' => false,
            'value' => function ($model) {
                return \app\components\Tanggal::toReadableDate($model->tanggal_upload_bukti);
            }
        ],
        // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
        [
            'attribute' => 'tanggal_konfirmasi',
            'format' => 'raw',
            'filter' => false,
            'value' => function ($model) {
                return \app\components\Tanggal::toReadableDate($model->tanggal_konfirmasi);
            }
        ],
        // 'created_at',
        // 'updated_at',
        // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
        [
            'attribute' => 'status_id',
            'value' => function ($model) {
                return $model->status->name;
            }
        ],
    ],
]); ?>

                <hr />
                <?php $this->endBlock(); ?>



                


                <?= Tabs::widget(
                [
                    'id' => 'relation-tabs',
                    'encodeLabels' => false,
                    'items' => [[
                        'label'   => '<b class=""># ' . $model->nama . '</b>',
                        'content' => $this->blocks['app\models\Pembayaran'],
                        'active'  => true,
                    ],]
                ]
            );
            ?>    
                <?php
            } else {
            ?>
                <div class="error-page">
                    <h2 class="headline text-info"><i class="fa fa-warning text-yellow"></i></h2>
                    <div class="error-content">
                        <h3>Peringatan, Data Tidak Ditemukan!</h3>
                        <p style="font-weight: bold; text-align:left">
                            Data Tidak Ditemukan, Cek Ulang Data Anda.
                        </p>
                    </div>
                </div>
            <?php
            }
            ?>
            
        </div>
    </div>
</div>