<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "amanah_pendanaan".
 *
 * @property integer $id
 * @property integer $pendanaan_id
 * @property string $amanah
 * @property integer $flag
 *
 * @property \app\models\Pendanaan $pendanaan
 * @property string $aliasModel
 */
abstract class AmanahPendanaan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'amanah_pendanaan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pendanaan_id', 'amanah'], 'required'],
            [['pendanaan_id', 'flag'], 'integer'],
            [['amanah'], 'string'],
            [['pendanaan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pendanaan::className(), 'targetAttribute' => ['pendanaan_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pendanaan_id' => 'Pendanaan ID',
            'amanah' => 'Amanah',
            'flag' => 'Flag',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPendanaan()
    {
        return $this->hasOne(\app\models\Pendanaan::className(), ['id' => 'pendanaan_id']);
    }




}
