<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "bank".
 *
 * @property integer $id
 * @property string $name
 * @property string $logo
 *
 * @property \app\models\MarketingDataUser[] $marketingDataUsers
 * @property \app\models\Pembayaran[] $pembayarans
 * @property string $aliasModel
 */
abstract class Bank extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bank';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'logo'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Nama Bank',
            'logo' => 'Logo',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMarketingDataUsers()
    {
        return $this->hasMany(\app\models\MarketingDataUser::className(), ['bank_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPembayarans()
    {
        return $this->hasMany(\app\models\Pembayaran::className(), ['bank_id' => 'id']);
    }




}
