<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\Url;

/**
 * This is the base-model class for table "berita".
 *
 * @property integer $id
 * @property integer $kategori_berita_id
 * @property integer $user_id
 * @property string $judul
 * @property string $gambar
 * @property string $isi
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\KategoriBerita $kategoriBerita
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class Berita extends \yii\db\ActiveRecord
{

    public function fields()
    {
        $parent = parent::fields();

        

        if (isset($parent['user_id'])) {
            unset($parent['user_id']);
            // $parent['_user_id'] = function ($model) {
            //     return $model->user_id;
            // };
            $parent['user'] = function ($model) {
                return $model->user->name;
            };
        }

        if (isset($parent['kategori_berita_id'])) {
            unset($parent['kategori_berita_id']);
            // $parent['_kategori_berita_id'] = function ($model) {
            //     return $model->kategori_berita_id;
            // };
            $parent['kategori_berita'] = function ($model) {
                return $model->kategoriBerita;
            };
        }
        if (isset($parent['gambar'])) {
            unset($parent['gambar']);
            // $parent['_gambar'] = function ($model) {
            //     return $model->gambar;
            // };
            $parent['gambar'] = function ($model) {
                $file = $model->gambar;
                // $model->tanggal_received=date('Y-m-d H:i:s');
                return $path = "http://i-salam.id/web/uploads/berita/" . $file;
            };
            
        }
        if (!isset($parent['full_link'])) {
            unset($parent['full_link']);
            // $parent['_full_link'] = function ($model) {
            //     return $model->full_link;
            // };
            $parent['full_link'] = function ($model) {
                $path = "http://i-salam.id/web/detail-berita?id=";
                $pembayar = Url::to(['home/detail-berita', 'id' => $model->slug]);
                return $pembayar;
            };
            
        }
        // if (isset($parent['isi'])) {
        //     unset($parent['isi']);
        //     // $parent['_isi'] = function ($model) {
        //     //     return $model->isi;
        //     // };
        //     $parent['isi'] = function ($model) {
        //         $text = strip_tags($model->isi);
        //         // $model->tanggal_received=date('Y-m-d H:i:s');
        //         return $text;
        //     };
            
        // }
        if(isset($parent['view_count'])){
            unset($parent['view_count']);

            $parent['dilihat'] = function ($model){
            $interval = $model->view_count;
            return $interval." kali";
            };
        }
        if(isset($parent['created_at'])){
            unset($parent['created_at']);

            $parent['created_at'] = function ($model){
               return \app\components\Tanggal::toReadableDate($model->created_at,false);
            };
        }
        return $parent;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'berita';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => date("Y-m-d H:i:s"),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['kategori_berita_id', 'user_id', 'judul', 'slug', 'isi'], 'required'],
            [['kategori_berita_id', 'user_id'], 'integer'],
            [['isi'], 'string'],
            [['judul', 'gambar'], 'string', 'max' => 255],
            [['kategori_berita_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\KategoriBerita::className(), 'targetAttribute' => ['kategori_berita_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'kategori_berita_id' => 'Kategori Berita',
            'user_id' => 'User',
            'judul' => 'Judul',
            'gambar' => 'Gambar',
            'isi' => 'Isi',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKategoriBerita()
    {
        return $this->hasOne(\app\models\KategoriBerita::className(), ['id' => 'kategori_berita_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }




}
