<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "dokumen_kontrak".
 *
 * @property integer $id
 * @property integer $id_pendanaan
 * @property integer $id_user
 * @property string $nama_file
 *
 * @property \app\models\Pendanaan $pendanaan
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class DokumenKontrak extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dokumen_kontrak';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_pendanaan', 'id_user', 'nama_file'], 'required'],
            [['id_pendanaan', 'id_user'], 'integer'],
            [['nama_file'], 'string', 'max' => 255],
            [['id_pendanaan'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pendanaan::className(), 'targetAttribute' => ['id_pendanaan' => 'id']],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['id_user' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_pendanaan' => 'Id Pendanaan',
            'id_user' => 'Id User',
            'nama_file' => 'Nama File',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPendanaan()
    {
        return $this->hasOne(\app\models\Pendanaan::className(), ['id' => 'id_pendanaan']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'id_user']);
    }




}
