<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "hubungi_kami".
 *
 * @property integer $id
 * @property string $nama
 * @property string $nomor_hp
 * @property integer $tema_hubungi_kami_id
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\TemaHubungiKami $temaHubungiKami
 * @property string $aliasModel
 */
abstract class HubungiKami extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hubungi_kami';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => date("Y-m-d H:i:s"),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'nomor_hp', 'tema_hubungi_kami_id', 'status'], 'required'],
            [['tema_hubungi_kami_id', 'status'], 'integer'],
            [['nama', 'nomor_hp'], 'string', 'max' => 255],
            [['tema_hubungi_kami_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TemaHubungiKami::className(), 'targetAttribute' => ['tema_hubungi_kami_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'nomor_hp' => 'Nomor Hp',
            'tema_hubungi_kami_id' => 'Tema Hubungi Kami',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTemaHubungiKami()
    {
        return $this->hasOne(\app\models\TemaHubungiKami::className(), ['id' => 'tema_hubungi_kami_id']);
    }




}
