<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "kegiatan_pendanaan".
 *
 * @property integer $id
 * @property integer $pendanaan_id
 * @property string $kegiatan
 * @property string $foto
 * 
 * @property \app\models\Pendanaan $pendanaan
 * @property string $aliasModel
 */
abstract class KegiatanPendanaan extends \yii\db\ActiveRecord
{

    public function fields()
    {
        $parent = parent::fields();
        if (isset($parent['pendanaan_id'])) {
            unset($parent['pendanaan_id']);
            // $parent['_user_id'] = function ($model) {
            //     return $model->user_id;
            // };
            $parent['pendanaan'] = function ($model) {
                return $model->pendanaan;
            };
        }
        // if (isset($parent['foto'])) {
        //     unset($parent['foto']);
        //     $parent['foto'] = function ($model) {
        //         return Yii::getAlias("@file/kegiatan/$model->foto");
        //     };
        // }
        // if (isset($parent['created_at'])) {
        //     unset($parent['created_at']);

        //     $parent['created_at'] = function ($model) {
        //         return \app\components\Tanggal::toReadableDate($model->created_at, false);
        //     };
        // }

        return $parent;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'kegiatan_pendanaan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pendanaan_id', 'kegiatan', 'foto'], 'required'],
            [['pendanaan_id'], 'integer'],
            [['kegiatan'], 'string'],
            [['foto'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pendanaan_id' => 'Pendanaan',
            'kegiatan' => 'Kegiatan',
            'foto' => 'Foto',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPendanaan()
    {
        return $this->hasOne(\app\models\Pendanaan::className(), ['id' => 'pendanaan_id']);
    }
}
