<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "kegiatan_pendanaan".
 *
 * @property integer $id
 * @property integer $pendanaan_id
 * @property string $kegiatan
 * @property string $foto
 * @property string $aliasModel
 */
abstract class KegiatanPendanaan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'kegiatan_pendanaan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pendanaan_id', 'kegiatan', 'foto'], 'required'],
            [['pendanaan_id'], 'integer'],
            [['kegiatan'], 'string'],
            [['foto'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pendanaan_id' => 'Pendanaan',
            'kegiatan' => 'Kegiatan',
            'foto' => 'Foto',
        ];
    }
/**
     * @return \yii\db\ActiveQuery
     */
    public function getPendanaan()
    {
        return $this->hasOne(\app\models\Pendanaan::className(), ['id' => 'pendanaan_id']);
    }



}
