<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "kontak".
 *
 * @property integer $id
 * @property string $nama_kontak
 * @property string $nomor_telepon
 * @property string $aliasModel
 */
abstract class Kontak extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'kontak';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama_kontak', 'nomor_telepon'], 'required'],
            [['nama_kontak'], 'string', 'max' => 255],
            [['nomor_telepon'], 'string', 'max' => 20]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama_kontak' => 'Nama Kontak',
            'nomor_telepon' => 'Nomor Telepon',
        ];
    }




}
