<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "log_activity".
 *
 * @property integer $id_log
 * @property string $name
 * @property string $debit
 * @property string $kredit
 * @property string $tanggal
 * @property string $keterangan
 * @property string $aliasModel
 */
abstract class LogActivity extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'log_activity';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'debit', 'kredit', 'tanggal', 'keterangan'], 'required'],
            [['tanggal'], 'safe'],
            [['keterangan'], 'string'],
            [['name'], 'string', 'max' => 250],
            [['debit', 'kredit'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_log' => 'Id Log',
            'name' => 'Name',
            'debit' => 'Debit',
            'kredit' => 'Kredit',
            'tanggal' => 'Tanggal',
            'keterangan' => 'Keterangan',
        ];
    }




}
