<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pembayaran".
 *
 * @property integer $id
 * @property string $nama
 * @property integer $nominal
 * @property string $bukti_transaksi
 * @property integer $user_id
 * @property integer $marketing_id
 * @property integer $bank_id
 * @property integer $pendanaan_id
 * @property integer $status_id
 *
 * @property \app\models\Bank $bank
 * @property \app\models\Pendanaan $pendanaan
 * @property \app\models\Status $status
 * @property \app\models\User $user
 * @property \app\models\User $marketing
 * @property string $aliasModel
 */
abstract class Pembayaran extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pembayaran';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nominal', 'user_id', 'marketing_id', 'bank_id', 'pendanaan_id', 'status_id'], 'integer'],
            [['user_id', 'bank_id', 'pendanaan_id', 'status_id'], 'required'],
            [['nama', 'bukti_transaksi'], 'string', 'max' => 255],
            [['bank_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Bank::className(), 'targetAttribute' => ['bank_id' => 'id']],
            [['pendanaan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pendanaan::className(), 'targetAttribute' => ['pendanaan_id' => 'id']],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Status::className(), 'targetAttribute' => ['status_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['marketing_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['marketing_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'nominal' => 'Nominal',
            'bukti_transaksi' => 'Bukti Transaksi',
            'user_id' => 'User ID',
            'marketing_id' => 'Marketing ID',
            'bank_id' => 'Bank ID',
            'pendanaan_id' => 'Pendanaan ID',
            'status_id' => 'Status ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBank()
    {
        return $this->hasOne(\app\models\Bank::className(), ['id' => 'bank_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPendanaan()
    {
        return $this->hasOne(\app\models\Pendanaan::className(), ['id' => 'pendanaan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(\app\models\Status::className(), ['id' => 'status_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMarketing()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'marketing_id']);
    }




}
