<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the base-model class for table "pencairan".
 *
 * @property integer $id
 * @property integer $pendanaan_id
 * @property integer $nominal
 * @property integer $tanggal
 * @property string $created_at
 *
 * @property \app\models\Pendanaan $pendanaan
 * @property string $aliasModel
 */
abstract class Pencairan extends \yii\db\ActiveRecord
{

    public function fields()
    {
        $parent = parent::fields();
        if (isset($parent['pendanaan_id'])) {
            unset($parent['pendanaan_id']);
            // $parent['_pendanaan_id'] = function ($model) {
            //     return $model->pendanaan_id;
            // };
            $parent['pendanaan'] = function ($model) {
                return $model->pendanaan;
            };
        }

        return $parent;
    }


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pencairan';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => false,
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pendanaan_id', 'nominal', 'tanggal'], 'required'],
            [['pendanaan_id', 'nominal'], 'integer'],
            [['tanggal'], 'safe'],
            [['pendanaan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pendanaan::className(), 'targetAttribute' => ['pendanaan_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pendanaan_id' => 'Pendanaan ID',
            'nominal' => 'Nominal',
            'tanggal' => 'Tanggal',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPendanaan()
    {
        return $this->hasOne(\app\models\Pendanaan::className(), ['id' => 'pendanaan_id']);
    }




}
