<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use app\models\Pendanaan;
use Yii;
use yii\db\Expression;

use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "pendapatan".
 *
 * @property integer $id
 * @property integer $id_pendanaan
 * @property string $nominal
 * @property string $created_at
 *
 * @property \app\models\Pendanaan $pendanaan
 * @property string $aliasModel
 */
abstract class Pendapatan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public function fields()
    {
        $parent = parent::fields();
        if (!isset($parent['total_jumlah_lembaran_all'])) {
            unset($parent['total_jumlah_lembaran_all']);

            $parent['total_jumlah_lembaran_all'] = function ($model) {
                $total_jumlah_lembaran_all = Pembayaran::find()->where(['pendanaan_id' => $model->id_pendanaan])->andWhere(['status_id' => 6])->andWhere(['!=', 'jumlah_lembaran', 0])->sum('jumlah_lembaran');
                return $total_jumlah_lembaran_all;
            };
        }

        // $total_pendapatan_all = $pendapatan1->nominal / $total_jumlah_lembaran_all;
        if (!isset($parent['total_pendapatan_all'])) {
            unset($parent['total_pendapatan_all']);

            $parent['total_pendapatan_all'] = function ($model) {
                $total_jumlah_lembaran_all = Pembayaran::find()->where(['pendanaan_id' => $model->id_pendanaan])->andWhere(['status_id' => 6])->andWhere(['!=', 'jumlah_lembaran', 0])->sum('jumlah_lembaran');
                $total_pendapatan_all = $model->nominal / $total_jumlah_lembaran_all;
                return $total_pendapatan_all;
            };
        }

        if (!isset($parent['nama_pendanaan'])) {
            unset($parent['nama_pendanaan']);

            $parent['nama_pendanaan'] = function ($model) {
                $nama_pendanaan = Pendanaan::find()->select('nama_pendanaan')->where(['id' => $model->id_pendanaan])->one();
                return $nama_pendanaan;
            };
        }
        return $parent;
    }
    public static function tableName()
    {
        return 'pendapatan';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => false,
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_pendanaan', 'nominal'], 'required'],
            [['id_pendanaan'], 'integer'],
            [['nominal'], 'string', 'max' => 255],
            [['id_pendanaan'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pendanaan::className(), 'targetAttribute' => ['id_pendanaan' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_pendanaan' => 'Pendanaan',
            'nominal' => 'Nominal',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPendanaan()
    {
        return $this->hasOne(\app\models\Pendanaan::className(), ['id' => 'id_pendanaan']);
    }

    public function getPendanaanAktif()
    {
        return $this->getPendanaan()->where(['status_lembaran' => 1]);
    }
}
