<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pendanaan".
 *
 * @property integer $id
 * @property string $nama_pendanaan
 * @property string $foto
 * @property string $uraian
 * @property integer $nominal
 * @property string $pendanaan_berakhir
 * @property integer $user_id
 * @property integer $kategori_pendanaan_id
 * @property integer $status_id
 *
 * @property \app\models\Pembayaran[] $pembayarans
 * @property \app\models\KategoriPendanaan $kategoriPendanaan
 * @property \app\models\User $user
 * @property \app\models\Status $status
 * @property string $aliasModel
 */
abstract class Pendanaan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pendanaan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['uraian'], 'string'],
            [['nominal', 'user_id', 'kategori_pendanaan_id', 'status_id'], 'integer'],
            [['pendanaan_berakhir'], 'safe'],
            [['user_id', 'kategori_pendanaan_id', 'status_id'], 'required'],
            [['nama_pendanaan', 'foto'], 'string', 'max' => 255],
            [['kategori_pendanaan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\KategoriPendanaan::className(), 'targetAttribute' => ['kategori_pendanaan_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Status::className(), 'targetAttribute' => ['status_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama_pendanaan' => 'Nama Pendanaan',
            'foto' => 'Foto',
            'uraian' => 'Uraian',
            'nominal' => 'Nominal',
            'pendanaan_berakhir' => 'Pendanaan Berakhir',
            'user_id' => 'User',
            'kategori_pendanaan_id' => 'Kategori Pendanaan',
            'status_id' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPembayarans()
    {
        return $this->hasMany(\app\models\Pembayaran::className(), ['pendanaan_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKategoriPendanaan()
    {
        return $this->hasOne(\app\models\KategoriPendanaan::className(), ['id' => 'kategori_pendanaan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(\app\models\Status::className(), ['id' => 'status_id']);
    }




}
