<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "penyaluran".
 *
 * @property integer $id
 * @property integer $id_pendanaan
 * @property integer $nominal
 * @property string $tanggal_penyaluran
 * @property string $aliasModel
 */
abstract class Penyaluran extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'penyaluran';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_pendanaan', 'nominal', 'tanggal_penyaluran'], 'required'],
            [['id_pendanaan', 'nominal'], 'integer'],
            [['tanggal_penyaluran'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_pendanaan' => 'Pendanaan',
            'nominal' => 'Nominal',
            'tanggal_penyaluran' => 'Tanggal Penyaluran',
        ];
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPendanaan()
    {
        return $this->hasOne(\app\models\Pendanaan::className(), ['id' => 'id_pendanaan']);
    }

}
