<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "slides".
 *
 * @property integer $id
 * @property string $judul
 * @property string $sub_judul
 * @property string $gambar
 * @property integer $status
 * @property string $aliasModel
 */
abstract class Slides extends \yii\db\ActiveRecord
{

    public function fields()
    {
        $parent = parent::fields();

        
        if (isset($parent['gambar'])) {
            unset($parent['gambar']);
            // $parent['_gambar'] = function ($model) {
            //     return $model->gambar;
            // };
            $parent['gambar'] = function ($model) {
                $file = $model->gambar;
                // $model->tanggal_received=date('Y-m-d H:i:s');
                return $path = "http://i-salam.id/web/uploads/slides/" . $file;
            };
            
        }
        if (!isset($parent['aksi'])) {
            unset($parent['aksi']);
            // $parent['_link'] = function ($model) {
            //     return $model->link;
            // };
            $parent['aksi'] = function ($model) {
                // $model->tanggal_received=date('Y-m-d H:i:s');
                return $model->link;
            };
            
        }
        
        return $parent;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'slides';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['judul', 'sub_judul'], 'required'],
            [['link'], 'string'],
            [['status'], 'integer'],
            [['judul', 'sub_judul', 'gambar'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'judul' => 'Judul',
            'sub_judul' => 'Sub Judul',
            'gambar' => 'Gambar',
            'status' => 'Status',
        ];
    }




}
