<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "status".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \app\models\Pembayaran[] $pembayarans
 * @property \app\models\Pendanaan[] $pendanaans
 * @property string $aliasModel
 */
abstract class Status extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'status';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPembayarans()
    {
        return $this->hasMany(\app\models\Pembayaran::className(), ['status_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPendanaans()
    {
        return $this->hasMany(\app\models\Pendanaan::className(), ['status_id' => 'id']);
    }




}
