<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tema_hubungi_kami".
 *
 * @property integer $id
 * @property string $nama_tema
 *
 * @property \app\models\HubungiKami[] $hubungiKamis
 * @property string $aliasModel
 */
abstract class TemaHubungiKami extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tema_hubungi_kami';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama_tema'], 'required'],
            [['nama_tema'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama_tema' => 'Nama Tema',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHubungiKamis()
    {
        return $this->hasMany(\app\models\HubungiKami::className(), ['tema_hubungi_kami_id' => 'id']);
    }




}
