<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use kartik\file\FileInput;
use kartik\date\DatePicker;
/**
* @var yii\web\View $this
* @var app\models\Pembayaran $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="box box-info">
    <div class="box-body">
        <?php $form = ActiveForm::begin([
        'id' => 'Pembayaran',
        'layout' => 'horizontal',
        'enableClientValidation' => true,
        'errorSummaryCssClass' => 'error-summary alert alert-error'
        ]
        );
        ?>
        
			<?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'nominal')->textInput(['type'=>'number']) ?>
            
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'user_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\User::find()->all(), 'id', 'name'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['user_id'])),
    ]
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'marketing_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\User::find()->all(), 'id', 'name'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['marketing_id'])),
    ]
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'bank_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Bank::find()->all(), 'name', 'name'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['bank_id'])),
    ]
); ?>
<?=$form->field($model, 'tanggal_pembayaran')->widget(DatePicker::classname(), [
    'options' => ['placeholder' => 'Pilih Tanggal Pembayaran'],
    'readonly' => true,
    'pluginOptions' => [
        'format' => 'yyyy-m-d',
        'autocomplete' => "off",
        'autoclose'=>true,
    ],
]);?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'pendanaan_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Pendanaan::find()->all(), 'nama_pendanaan', 'nama_pendanaan'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['pendanaan_id'])),
    ]
); ?>
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'status_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\Status::find()->all(), 'id', 'name'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['status_id'])),
    ]
); ?>    <?= $form->field($model, 'bukti_transaksi',[
                    
    'options' => ['tag' => false]])->widget(FileInput::classname(), [
'options' => ['accept' => 'file/*'],
'pluginOptions' => [
    'allowedFileExtensions' => ['png','jpg','jpeg'],
    'maxFileSize' => 6500,
    'showRemove' => false,
    'showUpload' => false,
    'showCaption' => false,
    'dropZoneEnabled' => false,
    'browseLabel' => 'Upload File',
],
]);?>    <hr/>
        <?php echo $form->errorSummary($model); ?>
        <div class="row">
            <div class="col-md-offset-3 col-md-10">
                <?=  Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                <?=  Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>