<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\web\View;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\PembayaranSearch $searchModel
 */

$this->title = 'Pembayaran';
$this->params['breadcrumbs'][] = $this->title;
?>

<p>
    <?= Html::a('<i class="fa fa-plus"></i> Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?>
</p>


<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
<div class="box-body">

<div class="row">
    <div class="col-md-12">
        <label><strong>Pilih Tanggal Awal :</strong></label>
    </div>
    <div class="col-md-12">
        <input id="tanggal1" type="text" class="datepicker form-control"
               value="<?php echo date("Y-m-d"); ?>" style="text-align: center">
    </div>
</div>
<br/>
<div class="row">
    <div class="col-md-12">
        <label><strong>Pilih Tanggal Akhir :</strong></label>
    </div>
    <div class="col-md-12">
        <input id="tanggal2" type="text" class="datepicker form-control"
               value="<?php echo date("Y-m-d"); ?>" style="text-align: center">
    </div>
</div>
<br/>
<hr />

<div class="row">
    <div class="clearfix"></div>
    <div class="col-md-12">
        <a class="btn btn-success btn-block" id="cetak" target="_blank" >Export Excel</a>
    </div>
</div>
</div>
<div class="box box-info">
    <div class="box-body">
        <div class="table-responsive">
            <?= GridView::widget([
                'layout' => '{summary}{pager}{items}{pager}',
                'dataProvider' => $dataProvider,
                'pager'        => [
                    'class'          => yii\widgets\LinkPager::className(),
                    'firstPageLabel' => 'First',
                    'lastPageLabel'  => 'Last'
                ],
                'filterModel' => $searchModel,
                'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                'headerRowOptions' => ['class' => 'x'],
                'columns' => [

                    \app\components\ActionButton::getButtons(),

                    'nama',
                    [
                        'attribute' => 'nominal',
                        'label' => 'Nominal',
                        'format' => 'raw',
                        'filter' => false,
                        'value' => function ($model) {

                            return \app\components\Angka::toReadableHarga($model->nominal);
                        },
                    ],
                    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                    [
                        'attribute' => 'user_id',
                        'value' => function ($model) {
                            return $model->user->name;
                        }
                    ],
                    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                    // [
                    //     'attribute' => 'jenis_pembayaran_id',
                    //     'value' => function ($model) {
                    //         if($model->jenis_pembayaran_id != null){
                    //             return $model->jenisPembayaran->nama_jenis;
                    //         }else{
                    //             return "Belum Melakukan Pembayaran";
                    //         }
                    //     }
                    // ],
                    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat

                    [
                        'attribute' => 'pendanaan_id',
                        'value' => function ($model) {
                            return $model->pendanaan->nama_pendanaan;
                        }
                    ],
                    [
                        'attribute' => 'created_at',
                        'label' => 'Tanggal Buat Pembayaran',
                        'format' => 'raw',
                        'filter' => false,
                        'value' => function ($model) {
                            return \app\components\Tanggal::toReadableDate($model->created_at);
                        }
                    ],
                    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                    [
                        'attribute' => 'status_id',
                        'value' => function ($model) {
                            return $model->status->name;
                        }
                    ],

                    \app\components\ActionApproveButton::getButtonsPembayaran(),
                    /*// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat

			/*'bukti_transaksi'*/
                ],
            ]); ?>
        </div>
    </div>
</div>

<?php \yii\widgets\Pjax::end() ?>
<?php
$my_js = '
$(document).ready(function(){
$(".datepicker").datepicker({
format: "yyyy-mm-dd"
});
 $("#spinner").hide();
});
            $("#cetak").click(function() {
                var url = "'.Yii::$app->homeUrl.'pembayaran/export?"
                    + "t1=" + $("#tanggal1").val()
                    + "&t2=" + $("#tanggal2").val();

                window.open(url, "_blank","height=200,width=150");
            });
   ';
$this->registerJs($my_js, View::POS_END);
?>