<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\Pembayaran $model
*/

$this->title = 'Pembayaran ' . $model->nama;
$this->params['breadcrumbs'][] = ['label' => 'Pembayaran', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud pembayaran-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id],['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'Daftar Pembayaran', ['index'], ['class'=>'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="box box-info">
        <div class="box-body">
            <?php $this->beginBlock('app\models\Pembayaran'); ?>

            <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                    
                [
                    'attribute'=>'pendanaan_id',
                    'value' => function($model){
                        return $model->pendanaan->nama_pendanaan;
                    }
                ],
        'nama',
        [
            'attribute' => 'nominal',
            'label' => 'Nominal',
            'format' => 'raw',
            'filter' => false,
            'value' =>function ($model) {
    
                return \app\components\Angka::toReadableHarga($model->nominal);
        
            },
        ],
        [
            'attribute' =>'bukti_transaksi',
            'format' =>'html',
            'value' =>function($model) {
               return Html::img(\Yii::$app->request->BaseUrl.'/uploads/pembayaran/bukti_transaksi/'.$model->bukti_transaksi,['width'=>100]);
             },
         ],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'attribute'=>'user_id',
    'value' => function($model){
        return $model->user->name;
    }
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'attribute'=>'marketing_id',
    'value' => function($model){
        return $model->marketing->name;
    }
],
        'bank',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'attribute' => 'tanggal_pembayaran',
    'format' => 'raw',
    'filter' => false,
    'value' => function($model){
        return \app\components\Tanggal::toReadableDate($model->tanggal_pembayaran);
    }
],
        // 'created_at',
        // 'updated_at',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
                'attribute'=>'status_id',
                'value' => function($model){
                    return $model->status->name;
                }
            ],
            ],
            ]); ?>

            <hr/>

            <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id],
            [
            'class' => 'btn btn-danger',
            'data-confirm' => '' . 'Are you sure to delete this item?' . '',
            'data-method' => 'post',
            ]); ?>
            <?php $this->endBlock(); ?>


            
            <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># '.$model->nama.'</b>',
    'content' => $this->blocks['app\models\Pembayaran'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        </div>
    </div>
</div>
