<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\HubungiKami $model
 */

$this->title = 'Hubungi Kami ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Hubungi Kami', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud hubungi-kami-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'Daftar Hubungi Kami', ['index'], ['class' => 'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="box box-info">
        <div class="box-body">
            <?php $this->beginBlock('app\models\HubungiKami'); ?>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'id',
                    'nama',
                    'nomor_hp',
                    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'tema_hubungi_kami_id',
                        'value' => ($model->temaHubungiKami ?
                            Html::a('<i class="glyphicon glyphicon-list"></i>', ['tema-hubungi-kami/index']) . ' ' .
                            Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> ' . $model->temaHubungiKami->nama_tema, ['tema-hubungi-kami/view', 'id' => $model->temaHubungiKami->id,]) . ' ' .
                            Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'HubungiKami' => ['tema_hubungi_kami_id' => $model->tema_hubungi_kami_id]])
                            :
                            '<span class="label label-warning">?</span>'),
                    ],
                    [
                        'format' => 'html',
                        'attribute' => 'status',
                        'value' => (($model->status ==0) ? "Baru": (($model->status ==1)? "Telah Dihubuni" : "Status tidak Diketahui")),  
                    ],
                    'created_at',
                    'updated_at',
                ],
            ]); ?>

            <hr />

            <?= Html::a(
                '<span class="glyphicon glyphicon-trash"></span> ' . 'Delete',
                ['delete', 'id' => $model->id],
                [
                    'class' => 'btn btn-danger',
                    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
                    'data-method' => 'post',
                ]
            ); ?>
            <?php $this->endBlock(); ?>



            <?= Tabs::widget(
                [
                    'id' => 'relation-tabs',
                    'encodeLabels' => false,
                    'items' => [[
                        'label'   => '<b class=""># ' . $model->id . '</b>',
                        'content' => $this->blocks['app\models\HubungiKami'],
                        'active'  => true,
                    ],]
                ]
            );
            ?>
        </div>
    </div>
</div>